version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "16:00"
      timezone: "Europe/Berlin"
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
      time: "08:00"
      day: "saturday"
      timezone: "Europe/Berlin"
